"""Tabla de transacciones

Revision ID: 000ffa17f825
Revises: fcdc0beae7a9
Create Date: 2023-02-13 18:29:37.733635

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000ffa17f825"
down_revision = "fcdc0beae7a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(name="transaction_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "verified", "rejected", name="transaction_status"
            ),
            nullable=False,
        ),
        sa.Column("total_amount", sa.DECIMAL(), nullable=False),
        sa.Column("transaction_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "transactions_user_id_index", ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("transactions_user_id_index")

    op.drop_table("transactions")
    op.execute("DROP TYPE transaction_status;")
    # ### end Alembic commands ###
