"""Tipando_PaymentAccounts

Revision ID: 28bbeee7e7ab
Revises: 16c336b5b501
Create Date: 2023-02-19 08:55:21.136296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bbeee7e7ab'
down_revision = '16c336b5b501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('income', 'expense', name='transaction_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_accounts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
