"""Initial migration.

Revision ID: cc40fc3bdf4c
Revises: 
Create Date: 2023-02-11 13:14:14.393680

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc40fc3bdf4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # , create_type=False
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_password_change", sa.Date(), nullable=True),
        sa.Column("last_login", sa.Date(), nullable=True),
        sa.Column(
            "user_type",
            sa.Enum("admin", "pro", "standard", name="user_type"),
            server_default="standard",
            nullable=True,
        ),
        sa.Column(
            "preferred_language_code",
            sa.Enum("es", "en", name="preferred_language_code"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.execute("DROP TYPE user_type;")
    op.execute("DROP TYPE preferred_language_code;")
    # ### end Alembic commands ###
