"""Categorias y subcategorias

Revision ID: fcdc0beae7a9
Revises: e9d65ba3cda3
Create Date: 2023-02-13 12:49:40.015734

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fcdc0beae7a9"
down_revision = "e9d65ba3cda3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column(
            "type",
            sa.Enum("income", "expense", name="transaction_type"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subcategories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subcategories")
    op.drop_table("categories")

    op.execute("DROP TYPE transaction_type;")
    # ### end Alembic commands ###
